// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/index.qtpl:1
package views

//line views/index.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/index.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/index.qtpl:2
type Card struct {
	Name        string `json:"name"`
	URL         string `json:"url"`
	Description string `json:"description"`
}

//line views/index.qtpl:9
func StreamPackageCard(qw422016 *qt422016.Writer, pkg_name, url, description string) {
//line views/index.qtpl:9
	qw422016.N().S(`
<div class="card">
    <h2>`)
//line views/index.qtpl:11
	qw422016.E().S(pkg_name)
//line views/index.qtpl:11
	qw422016.N().S(`</h2>
    <hr />
    <a href="https://pkg.go.dev/`)
//line views/index.qtpl:13
	qw422016.E().S(pkg_name)
//line views/index.qtpl:13
	qw422016.N().S(`">Documentation</a>
    <p>Repository: <a href="`)
//line views/index.qtpl:14
	qw422016.E().S(url)
//line views/index.qtpl:14
	qw422016.N().S(`">`)
//line views/index.qtpl:14
	qw422016.E().S(pkg_name)
//line views/index.qtpl:14
	qw422016.N().S(`</a></p>
    <p>`)
//line views/index.qtpl:15
	qw422016.E().S(description)
//line views/index.qtpl:15
	qw422016.N().S(`</p>
</div>
`)
//line views/index.qtpl:17
}

//line views/index.qtpl:17
func WritePackageCard(qq422016 qtio422016.Writer, pkg_name, url, description string) {
//line views/index.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/index.qtpl:17
	StreamPackageCard(qw422016, pkg_name, url, description)
//line views/index.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line views/index.qtpl:17
}

//line views/index.qtpl:17
func PackageCard(pkg_name, url, description string) string {
//line views/index.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line views/index.qtpl:17
	WritePackageCard(qb422016, pkg_name, url, description)
//line views/index.qtpl:17
	qs422016 := string(qb422016.B)
//line views/index.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line views/index.qtpl:17
	return qs422016
//line views/index.qtpl:17
}

//line views/index.qtpl:20
func StreamIndexPage(qw422016 *qt422016.Writer, cards []Card) {
//line views/index.qtpl:20
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Package Server</title>

    <style>html{display:block;background-color:#F5F0BB;color:#3D3C42;font-weight:800}.box{display:flex}.ma{height:2.0;margin:auto;margin-bottom:1.5em}input[type="text"]{width:850px;height:100%;border-color:black;border-radius:0}input[type="submit"]{height:100%;margin-bottom:0;border-color:black;border-radius:0}hr{height:.25em;background-color:#73A9AD;border-radius:1em;border-color:#73A9AD}a,a:link,a:hover,a:visited,a:active{color:#3D3C42;text-decoration:underline}.card{width:900px;margin:1.5em auto;padding:1.7em;background-color:#90C8AC;border-radius:.5em}@media (max-width:1000px){.card{margin:1em auto;width:auto}.ma{width:90vw;margin:auto;margin-bottom:3em}input[type="text"]{width:85%;margin:2em auto}input[type="submit"]{width:10%}}</style>
</head>

<body>
    <h1>Package Server</h1>
    <hr />
    <form action="/" method="get" class="box">
        <div class="ma">
            <input type="text" name="q" id="search" /><input type="submit">
        </div>
    </form>

    <div id="cards">`)
//line views/index.qtpl:42
	for _, v := range cards {
//line views/index.qtpl:42
		StreamPackageCard(qw422016, v.Name, v.URL, v.Description)
//line views/index.qtpl:42
	}
//line views/index.qtpl:42
	qw422016.N().S(`</div>

    <div class="card">
        <a href=""><button style="width: 40%">Prev</button></a>
        <a href=""><button style="width: 40%">Next</button></a>
    </div>
</body>

</html>
`)
//line views/index.qtpl:51
}

//line views/index.qtpl:51
func WriteIndexPage(qq422016 qtio422016.Writer, cards []Card) {
//line views/index.qtpl:51
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/index.qtpl:51
	StreamIndexPage(qw422016, cards)
//line views/index.qtpl:51
	qt422016.ReleaseWriter(qw422016)
//line views/index.qtpl:51
}

//line views/index.qtpl:51
func IndexPage(cards []Card) string {
//line views/index.qtpl:51
	qb422016 := qt422016.AcquireByteBuffer()
//line views/index.qtpl:51
	WriteIndexPage(qb422016, cards)
//line views/index.qtpl:51
	qs422016 := string(qb422016.B)
//line views/index.qtpl:51
	qt422016.ReleaseByteBuffer(qb422016)
//line views/index.qtpl:51
	return qs422016
//line views/index.qtpl:51
}
