// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/index.qtpl:1
package views

//line views/index.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/index.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/index.qtpl:2
type Card struct {
	Name        string `json:"name"`
	URL         string `json:"url"`
	Description string `json:"description"`
}

//line views/index.qtpl:9
func StreamPackageCard(qw422016 *qt422016.Writer, pkg_name, url, description string) {
//line views/index.qtpl:9
	qw422016.N().S(`
<div class="card">
    <h2>`)
//line views/index.qtpl:11
	qw422016.E().S(pkg_name)
//line views/index.qtpl:11
	qw422016.N().S(`</h2>
    <hr />
    <a href="https://pkg.go.dev/`)
//line views/index.qtpl:13
	qw422016.E().S(pkg_name)
//line views/index.qtpl:13
	qw422016.N().S(`">Documentation</a>
    <p>Repository: <a href="`)
//line views/index.qtpl:14
	qw422016.E().S(url)
//line views/index.qtpl:14
	qw422016.N().S(`">`)
//line views/index.qtpl:14
	qw422016.E().S(pkg_name)
//line views/index.qtpl:14
	qw422016.N().S(`</a></p>
    <p>`)
//line views/index.qtpl:15
	qw422016.E().S(description)
//line views/index.qtpl:15
	qw422016.N().S(`</p>
</div>
`)
//line views/index.qtpl:17
}

//line views/index.qtpl:17
func WritePackageCard(qq422016 qtio422016.Writer, pkg_name, url, description string) {
//line views/index.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/index.qtpl:17
	StreamPackageCard(qw422016, pkg_name, url, description)
//line views/index.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line views/index.qtpl:17
}

//line views/index.qtpl:17
func PackageCard(pkg_name, url, description string) string {
//line views/index.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line views/index.qtpl:17
	WritePackageCard(qb422016, pkg_name, url, description)
//line views/index.qtpl:17
	qs422016 := string(qb422016.B)
//line views/index.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line views/index.qtpl:17
	return qs422016
//line views/index.qtpl:17
}

//line views/index.qtpl:20
func StreamIndexPage(qw422016 *qt422016.Writer, cards []Card, prev, next string) {
//line views/index.qtpl:20
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Package Server</title>
</head>

<body>
    <h1><a href="/">Package Server</a></h1>
    <hr />
    <form action="/" method="get" class="box">
        <div class="ma">
            <input type="text" name="q" id="search" placeholder="Search" /><input type="submit">
        </div>
    </form>

    <div id="cards">`)
//line views/index.qtpl:40
	for _, v := range cards {
//line views/index.qtpl:40
		StreamPackageCard(qw422016, v.Name, v.URL, v.Description)
//line views/index.qtpl:40
	}
//line views/index.qtpl:40
	qw422016.N().S(`</div>

    <div class="card">
        <a href="?`)
//line views/index.qtpl:43
	qw422016.E().S(prev)
//line views/index.qtpl:43
	qw422016.N().S(`" id="prev"><button style="width: 40%">Prev</button></a>
        <a href="?`)
//line views/index.qtpl:44
	qw422016.E().S(next)
//line views/index.qtpl:44
	qw422016.N().S(`" id="next"><button style="width: 40%">Next</button></a>
    </div>
</body>

</html>
`)
//line views/index.qtpl:49
}

//line views/index.qtpl:49
func WriteIndexPage(qq422016 qtio422016.Writer, cards []Card, prev, next string) {
//line views/index.qtpl:49
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/index.qtpl:49
	StreamIndexPage(qw422016, cards, prev, next)
//line views/index.qtpl:49
	qt422016.ReleaseWriter(qw422016)
//line views/index.qtpl:49
}

//line views/index.qtpl:49
func IndexPage(cards []Card, prev, next string) string {
//line views/index.qtpl:49
	qb422016 := qt422016.AcquireByteBuffer()
//line views/index.qtpl:49
	WriteIndexPage(qb422016, cards, prev, next)
//line views/index.qtpl:49
	qs422016 := string(qb422016.B)
//line views/index.qtpl:49
	qt422016.ReleaseByteBuffer(qb422016)
//line views/index.qtpl:49
	return qs422016
//line views/index.qtpl:49
}
